Merging fixes into trunk:
Revision: [4199]
Fixes for:
Ticket #1394 setFlash with layout fails because of missing params to View
Ticket #1480 Incorrect urls with Plugins
Ticket #1670 HtmlHelper::selectTag: problem when is_array($selected)
Ticket #1685 Router::url can cause incorrect links
Ticket #1774 Route::url() don't find the right route
Ticket #1776 Postgres - after each insert atempting to retrieve last inserted id from seq.
Ticket #1765 Dispatcher, route and plugins

Adding doc comments to EmailComponent
Removed ) in I10n::__l10nCatalog['lv'] 

Revision: [4196]
"Merging fixes made in 1.2 branch.
Adding fixes for Ticket #1785 hourOptionTag can never be empty
and Ticket #1792 dateTimeOptionTag hour is always set to 12 even if selected is null"

Revision: [4195]
Adding URL fix for Ticket #1679

Revision: [4182]
cli acl.php fixes. #1773 and #1780

Revision: [4169]
Adding 1.1 fix for Ticket #1794

Revision: [4168]
Adding NOT query conditions fix for Ticket #1793

Revision: [4166]
Adding beforeFind() reference fix for 1.1 (#1784)

Revision: [4131]
Adding fix for Ticket #1797, and URL fix for Ticket #1755

Revision: [4130]
fix for #1789

Revision: 4118
Mering changes from [4117] Configure::read()

Revision: [4105]
Adding loadControllers() fix for Ticket #1745

Revision: [4103]
Fixing error messages in File::create (ticket #1770)

Revision: [4100]
Changing Model::del to check for existence of itself before allowing deletes

Revision: [4095]
Checking if model exists when setting 'created' field, to enable use with custom IDs

Revision: [4093]
Adding fix for Ticket #1746

Revision: [4091]
Adding fix for Ticket #1740

Revision: [4088]
Typo (ticket #1738)

Revision: [4079]
Adding fix for ErrorHandler throwing error when Dispatcher class is not in memory

Revision: [4078]
Adding fix for Ticket #1732

Revision: [4074]
Adding fix for View::element().
params variable was reset to an array
Added the method to 1.2.x.x branch also

Revision: [4073]
Adding fix for Ticket #1731

Revision: [4072]
Fixing error in Router::parse() when no params are passed.
Initialized $pass variable as an array before the foreach

Revision: [4071]
Adding fix for Ticket #1721

Revision: [4070]
Adding fix for Ticket #1723

Revision: [4066]
Adding fix when using database storage for sessions.

This fixes
Fatal error: Class 'ConnectionManager' not found in
/cake/libs/session.php on line 445

Removed validators.php
Updated svnconfig.txt

git-svn-id: https://svn.cakephp.org/repo/branches/1.2.x.x@4202 3807eeeb-6ff5-0310-8944-8be069107fe0